### ISSUE TITLE
BART-both的总体摘要

### ISSUE THREAD

**Issue by neugwh** [xnliang98/bart-glc#1]
您好，对于BART-both这个baseline,你们是怎么得到总体摘要的结果的，是直接将用户摘要和客服摘要按序拼接嘛

**Comment by xnliang98** [comment]
> 您好，对于BART-both这个baseline,你们是怎么得到总体摘要的结果的，是直接将用户摘要和客服摘要按序拼接嘛

是的原始数据集是这么进行标注的。

**Comment by neugwh** [comment]
好的，感谢



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Xinnian ***@***.***> |
| 日期 | 2023年03月18日 18:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xnliang98/bart-glc] BART-both的总体摘要 (Issue #1) |

您好，对于BART-both这个baseline,你们是怎么得到总体摘要的结果的，是直接将用户摘要和客服摘要按序拼接嘛

是的原始数据集是这么进行标注的。
